added the commitable field to a project
git-svn-id: file:///var/lib/codepot/svnrepo/codepot/trunk@80 acb928ee-5b15-407b-8704-3b33df051210

diff --git a/codepot/etc/start-commit b/codepot/etc/start-commit
--- a/codepot/etc/start-commit
+++ b/codepot/etc/start-commit
@@ -3,17 +3,17 @@
 REPOBASE="`basename "${1}"`"
 USER="${2}"
 
-ans="`wget -q -O- "%API%/projectHasMember/${REPOBASE}/${USER}" 2>/dev/null`"
+ans="`wget -q -O- "%API%/projectIsCommitable/${REPOBASE}/${USER}" 2>/dev/null`"
 [ "${ans}" = "YES" ] && exit 0
 
 [ "${ans}" = "NO" ] && {
 	echo "-------------------------------------------------------------" >&2
-	echo " ${USER} is not a member of ${REPOBASE}" >&2
+	echo " ${REPOBASE} is read-only or ${USER} is not a member of ${REPOBASE}" >&2
 	echo "-------------------------------------------------------------" >&2
 	exit 1
 }
 
 echo "---------------------------------------------------------------------" >&2
-echo " Failed to check membership of ${REPOBASE} for ${USER}" >&2
+echo " Failed to check commitability of ${REPOBASE} for ${USER}" >&2
 echo "---------------------------------------------------------------------" >&2
 exit 1
